# Site
name: "The Write Ahead Log"
title: "The Write Ahead Log"
description: "Platform and Product Engineering Journal"
logo: 'assets/images/plf-logo.svg'
favicon: 'assets/images/logo.png'
baseurl: /blog
google_analytics: 'G-PWW2W71JX1'
#disqus: 'demowebsite'
mailchimp-list: 'https://platformatory.us17.list-manage.com/subscribe/post?u=8cc2e44e80300ae193f198bcc&amp;id=6246b12a61'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  p6:
    name: pavan
    display_name: Pavan Keshavamurthy
    gravatar: a92e3c1140c93b65879c69ecf47bb1b5
    email: pavan@platformatory.io
    web: https://platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Pavan is a cofounder and principal consultant at Platformatory. While not being a handyman for everything at Platformatory, he is likely indluging in random walks (around Bangalore), music or herding kids"
  badri:
    name: badri
    display_name: Lakshminarasimhan Parthasarathy    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: lakshmi@platformatory.io
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Principal Engineer at Platformatory; Musician"
  srikanth:
    name: srikanth
    display_name: Srikanth Pai
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: srikanth@platformatory.io
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Consultant at Platformatory;"
  dasa:
    name: dasa
    display_name: Dasa Sathyan
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: srikanth@platformatory.io
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Sr Consultant at Platformatory;"
  ashwin:
    name: ashwin
    display_name: Ashwin Venkatesan
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: srikanth@platformatory.io
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Sr Consultant at Platformatory;"
  venkatesh:
    name: venkatesh
    display_name: Venkatesh Keshavamurthy
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: srikanth@platformatory.io
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Data Engineer at Platformatory;"
  kiran:
    name: kiran
    display_name: Kiran Sreevastav
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: srikanth@platformatory.io
    web: https://www.platformatory.io
    twitter: https://twitter.com/platformatory
    description: "Data Engineer at Platformatory;"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
#adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
